# Generated by Django 5.2.7 on 2025-11-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplace',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='foodplace',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodplace',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bakery', 'Bakery'), ('market', 'Market'), ('producer', 'Artisan Producer'), ('coffee', 'Coffee Shop'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
