# Generated by Django 5.2.7 on 2025-11-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_place_delete_foodplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.RemoveField(
            model_name='place',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='place',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
