# Generated by Django 5.2.7 on 2025-11-16 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('bakery', 'Bakery'), ('market', 'Market'), ('producer', 'Artisan Producer'), ('coffee', 'Coffee Shop'), ('other', 'Other')], default='restaurant', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
